// export const approvedHeader = ['S.No', 'Name', 'Venue Category', 'Address', 'Service', 'Cost Per Day', 'status'];
export const approvedHeader = ['S.No', 'Name', 'Address', 'status'];
export const approvedData = [
  {
    SNo: 1,
    Name: 'Aadhi Pet Center',
    Email: 'Apartment',
    address: 'Anna Nagar, Chennai',
    service: 'sitting',
    amenities: 'CCTV',
    optional: 'CCTV',
    cost: '180',
  },
  {
    SNo: 2,
    Name: 'John Pet Center',
    Email: 'Independent House',
    address: 'Chrompet, Chennai',
    service: 'Walking',
    amenities: 'Play Area',
    optional: 'Play Area',
    cost: 80,
  },
  {
    SNo: 3,
    Name: 'Arjun Pet Center',
    Email: 'National Community',
    address: 'Kolathur, Chennai',
    service: 'Photography',
    amenities: 'Training, sitting',
    optional: 'Caretakers',
    cost: 1000,
  },
  {
    SNo: 4,
    Name: 'George Pet Center',
    Email: 'Apartment',
    address: 'Perambur, Chennai',
    service: 'Guindy, Chennai',
    amenities: 'Grooming, sitting',
    optional: 'cage',
    cost: 120,
  },
];
// export const pendingHeader = ['S.No', 'Name', 'Venue Category', 'Address', 'Service', 'Cost Per Day', 'Status'];
export const pendingHeader = ['S.No', 'Name', 'Address', 'Status'];
export const pendingData = [
  {
    SNo: 1,
    Name: 'Aadhi Pet Center',
    Email: 'Apartment',
    address: 'Anna Nagar, Chennai',
    service: 'sitting',
    amenities: 'CCTV',
    optional: 'CCTV',
    cost: '500',
  },
  {
    SNo: 2,
    Name: 'John Pet Center',
    Email: 'Gated Community',
    address: 'Chrompet, Chennai',
    service: 'Walking',
    amenities: 'Play Area',
    optional: 'Play Area',
    cost: 800,
  },
  {
    SNo: 3,
    Name: 'Arjun Pet Center',
    Email: 'Apartment',
    address: 'Kolathur, Chennai',
    service: 'Photography',
    amenities: 'Training, sitting',
    optional: 'Caretakers',
    cost: 1000,
  },
  {
    SNo: 4,
    Name: 'George Pet Center',
    Email: 'Independent House',
    address: 'Perambur, Chennai',
    service: 'Guindy, Chennai',
    amenities: 'Grooming, sitting',
    optional: 'cage',
    cost: 1200,
  },
];
export const rejectedHeader = ['S.No', 'Name', 'Address', 'Status'];
export const rejectedData = [
  {
    SNo: 1,
    Name: 'Aadhi Pet Center',
    Email: 'Apartment',
    address: 'Anna Nagar, Chennai',
    service: 'sitting',
    amenities: 'CCTV',
    optional: 'CCTV',
    cost: '180',
  },
  {
    SNo: 2,
    Name: 'John Pet Center',
    Email: 'Gated Community',
    address: 'Chrompet, Chennai',
    service: 'Walking',
    amenities: 'Play Area',
    optional: 'Play Area',
    cost: 80,
  },
  {
    SNo: 3,
    Name: 'Arjun Pet Center',
    Email: 'Apartment',
    address: 'Kolathur, Chennai',
    service: 'Photography',
    amenities: 'Training, sitting',
    optional: 'Caretakers',
    cost: 1000,
  },
  {
    SNo: 4,
    Name: 'George Pet Center',
    Email: 'Independent House',
    address: 'Perambur, Chennai',
    service: 'Guindy, Chennai',
    amenities: 'Grooming, sitting',
    optional: 'cage',
    cost: 120,
  },
];
