export const venueBookedHeader = [
  'S.No',
  'Name',
  'Contact Number',
  'Pet Name',
  'Pet Count',
  'Services',
  'Venue',
  'No.Of.Days',
  'Cost',
  'Requirement',
];
export const venueBookedData = [
  {
    SNo: 1,
    Name: 'John',
    contact: '9884239346',
    petName: 'Jack,Joel,Brown',
    petCount: '3',
    venue: 'Aadhi Pet Center',
    noOfDays: '1',
    cost: '1220',
    requirement: 'Immediate',
  },
  {
    SNo: 2,
    Name: 'Arivu',
    contact: '9176254546',
    petName: 'White',
    petCount: '3',
    venue: 'Arun Pet Center',
    noOfDays: '1',
    cost: '1220',
    requirement: 'Within a week',
  },
  {
    SNo: 3,
    Name: 'Aadhi',
    contact: '9884239346',
    petName: 'Jack,Joel,Brown',
    petCount: '3',
    venue: 'Aadhi Pet Center',
    noOfDays: '1',
    cost: '1220',
    requirement: 'within a month',
  },
  {
    SNo: 1,
    Name: 'John',
    contact: '9884239346',
    petName: 'Jack,Joel,Brown',
    petCount: '3',
    venue: 'Aadhi Pet Center',
    noOfDays: '1',
    cost: '1220',
    requirement: 'within a week',
  },
];
export const serviceBookedHeader = [
  'S.No',
  'Name',
  'Contact Number',
  'Pet Name',
  'Pet Count',
  'Services',
  'Venue',
  'No.Of.Days',
  'Cost',
];
export const serviceBookedData = [
  {
    SNo: 1,
    Name: 'John',
    contact: '9884239346',
    petName: 'Jack,Joel,Brown',
    petCount: '3',
    venue: 'Aadhi Pet Center',
    hours: '1',
    cost: '1220',
  },
  {
    SNo: 2,
    Name: 'John',
    contact: '9884239346',
    petName: 'Jack,Joel,Brown',
    petCount: '3',
    venue: 'Aadhi Pet Center',
    hours: '1',
    cost: '1220',
  },
  {
    SNo: 3,
    Name: 'John',
    contact: '9884239346',
    petName: 'Jack,Joel,Brown',
    petCount: '3',
    venue: 'Aadhi Pet Center',
    hours: '1',
    cost: '1220',
  },
  {
    SNo: 4,
    Name: 'John',
    contact: '9884239346',
    petName: 'Jack,Joel,Brown',
    petCount: '3',
    venue: 'Aadhi Pet Center',
    hours: '1',
    cost: '1220',
  },
];
