export const approvedHeader = [
  'S.No',
  'Name',
  'Venue Category',
  'Address',
  // 'Service',
  // 'Amenities',
  // 'Option Available',
  'Cost Per Day',
  'Status',
];
export const approvedData = [
  {
    SNo: 1,
    Name: 'Aadhi Pet Center',
    Email: 'Apartment',
    address: 'Anna Nagar, Chennai',
    service: 'sitting',
    amenities: 'CCTV',
    optional: 'CCTV',
    cost: '500',
  },
  {
    SNo: 2,
    Name: 'John Pet Center',
    Email: 'House',
    address: 'Chrompet, Chennai',
    service: 'Walking',
    amenities: 'Play Area',
    optional: 'Play Area',
    cost: 800,
  },
  {
    SNo: 3,
    Name: 'Arjun Pet Center',
    Email: 'Independent House',
    address: 'Kolathur, Chennai',
    service: 'Photography',
    amenities: 'Training, sitting',
    optional: 'Caretakers',
    cost: 1000,
  },
  {
    SNo: 4,
    Name: 'George Pet Center',
    Email: 'Apartment',
    address: 'Perambur, Chennai',
    service: 'Guindy, Chennai',
    amenities: 'Grooming, sitting',
    optional: 'cage',
    cost: 1200,
  },
];
export const rejectedHeader = [
  'S.No',
  'Name',
  'Venue Category',
  'Address',
  // 'Service',
  // 'Amenities',
  // 'Option Available',
  'Cost Per Day',
  'Status',
];
export const rejectedData = [
  {
    SNo: 1,
    Name: 'Aadhi Pet Center',
    Email: 'Adhi123@gmail.com',
    address: 'Anna Nagar, Chennai',
    service: 'sitting',
    amenities: 'CCTV',
    optional: 'CCTV',
    cost: '500',
  },
  {
    SNo: 2,
    Name: 'John Pet Center',
    Email: 'Apartment',
    address: 'Chrompet, Chennai',
    service: 'Walking',
    amenities: 'Play Area',
    optional: 'Play Area',
    cost: 800,
  },
  {
    SNo: 3,
    Name: 'Arjun Pet Center',
    Email: 'Community',
    address: 'Kolathur, Chennai',
    service: 'Photography',
    amenities: 'Training, sitting',
    optional: 'Caretakers',
    cost: 1000,
  },
  {
    SNo: 4,
    Name: 'George Pet Center',
    Email: 'Independent House',
    address: 'Perambur, Chennai',
    service: 'Guindy, Chennai',
    amenities: 'Grooming, sitting',
    optional: 'cage',
    cost: 1200,
  },
];
export const pendingHeader = [
  'S.No',
  'Name',
  'Venue Category',
  'Address',
  // 'Service',
  // 'Amenities',
  // 'Option Available',
  'Cost Per Day',
  'Status',
];
export const pendingData = [
  {
    SNo: 1,
    Name: 'Aadhi Pet Center',
    Email: 'Apartment',
    address: 'Anna Nagar, Chennai',
    service: 'sitting',
    amenities: 'CCTV',
    optional: 'CCTV',
    cost: '500',
  },
  {
    SNo: 2,
    Name: 'John Pet Center',
    Email: 'Independent House',
    address: 'Independent House',
    service: 'Walking',
    amenities: 'Play Area',
    optional: 'Play Area',
    cost: 800,
  },
  {
    SNo: 3,
    Name: 'Arjun Pet Center',
    Email: 'Apartment',
    address: 'Kolathur, Chennai',
    service: 'Photography',
    amenities: 'Training, sitting',
    optional: 'Caretakers',
    cost: 1000,
  },
  {
    SNo: 4,
    Name: 'George Pet Center',
    Email: 'Apartment',
    address: 'Perambur, Chennai',
    service: 'Guindy, Chennai',
    amenities: 'Grooming, sitting',
    optional: 'cage',
    cost: 1200,
  },
];
