/// //////******* MASTERs********///////
export const CATEGORY_STATUS = 'CATEGORY_STATUS';
export const GET_ALL_PET_CATEGORY_LIST = 'GET_ALL_PET_CATEGORY_LIST';
export const GET_ALL_PET_CATEGORY_LIST_RESULT = 'GET_ALL_PET_CATEGORY_LIST_RESULT';

export const CREATE_PET_CATEGORY = 'CREATE_PET_CATEGORY';
export const CREATE_PET_CATEGORY_RESULT = 'CREATE_PET_CATEGORY_RESULT';

export const UPDATE_CREATE_PET_CATEGORY = 'UPDATE_CREATE_PET_CATEGORY';
export const UPDATE_CREATE_PET_CATEGORY_RESULT = 'UPDATE_CREATE_PET_CATEGORY_RESULT';

export const DELETE_PET_CATEGORY = 'DELETE_PET_CATEGORY';
export const DELETE_PET_CATEGORY_RESULT = 'DELETE_PET_CATEGORY_RESULT';

// eslint-disable-next-line spaced-comment
//////*** VENUE MASTERS *****////////

export const VENUE_STATUS = 'VENUE_STATUS';

export const CREATE_VENUE_MASTER = ' CREATE_VENUE_MASTER';
export const CREATE_VENUE_MASTER_RESULT = 'CREATE_VENUE_MASTER_RESULT';

export const GET_VENUE_MASTER = 'GET_VENUE_MASTER';
export const GET_VENUE_MASTER_RESULT = 'GET_VENUE_MASTER_RESULT';

export const UPDATE_VENUE_MASTER = 'UPDATE_VENUE_MASTER';
export const UPDATE_VENUE_MASTER_RESULT = 'UPDATE_VENUE_MASTER_RESULT';

export const DELETE_VENUE_MASTER = 'DELETE_VENUE_MASTER';
export const DELETE_VENUE_MASTER_RESULT = 'DELETE_VENUE_MASTER_RESULT';

/// /*** AMINITIES MASTERS  ***/////

export const AMENTIES_STATUS = 'AMENTIES_STATUS';
export const INSERT_AMENETIES_CHECK = 'INSERT_AMENETIES_CHECK';

export const GET_MASTER_LIST_ADMIN = 'GET_MASTER_LIST_ADMIN';
export const GET_MASTER_LIST_ADMIN_RESULT = 'GET_MASTER_LIST_ADMIN_RESULT';

export const AMENTIES_MASTER = 'AMENTIES_MASTER';
export const AMENTIES_MASTER_RESULT = 'AMENTIES_MASTER_RESULT';

export const UPDATE_AMENTIES_MASTER = 'UPDATE_AMENTIES_MASTER';
export const UPDATE_AMENTIES_MASTER_RESULT = 'UPDATE_AMENTIES_MASTER_RESULT';

export const DELETE_AMENTIES_MASTER = 'DELETE_AMENTIES_MASTER';
export const DELETE_AMENTIES_MASTER_RESULT = 'DELETE_AMENTIES_MASTER_RESULT';

/// *** OPTIONS MASTER *****/

export const OPTION_STATUS = 'OPTION_STATUS';
export const INSERT_STAUS_MESSEAGE = 'INSERT_STAUS_MESSEAGE';

export const GET_OPTIONS_APPLICABLE = 'GET_OPTIONS_APPLICABLE';
export const GET_OPTIONS_APPLICABLE_RESULT = 'GET_OPTIONS_APPLICABLE_RESULT';

export const CREATE_OPTIONS_MASTER = 'CREATE_OPTIONS_MASTER';
export const CREATE_OPTIONS_MASTER_RESULT = 'CREATE_OPTIONS_MASTER_RESULT';

export const UPDATE_OPTIONS_MASTER = 'UPDATE_OPTIONS_MASTER';
export const UPDATE_OPTIONS_MASTER_RESULT = ' UPDATE_OPTIONS_MASTER_RESULT';

export const DELETE_OPTONS_MASTER = 'DELETE_OPTONS_MASTER';
export const DELETE_OPTONS_MASTER_RESULT = 'DELETE_OPTONS_MASTER_RESULT';

/// /** SERVICE MASTER */

export const SERVICE_STATUS = 'SERVICE_STATUS';

export const GET_SERVICE_MASTER = 'GET_SERVICE_MASTER';
export const GET_SERVICE_MASTER_RESULT = 'GET_SERVICE_MASTER_RESULT';

export const CREATE_SERVICE_MASTER = 'CREATE_SERVICE_MASTER';
export const CREATE_SERVICE_MASTER_RESULT = 'CREATE_SERVICE_MASTER_RESULT';

export const UPDATED_SERVICE_MASTER = 'UPDATED_SERVICE_MASTER';
export const UPDATED_SERVICE_MASTER_RESULT = 'UPDATED_SERVICE_MASTER_RESULT';

export const DELETE_SERVICE_MASTER = 'DELETE_SERVICE_MASTER';
export const DELETE_SERVICE_MASTER_RESULT = 'DELETE_SERVICE_MASTER_RESULT';

/// *** VENUE SCREEN */

export const GET_VENUE_SPACE = 'GET_VENUE_SPACE';
export const GET_VENUE_SPACE_RESULTS = 'GET_VENUE_SPACE_RESULT';

//* ** VENUE SCREEN DETAILS ***/

export const GET_ALL_SPACE_LIST = 'GET_ALL_SPACE_LIST';
export const GET_ALL_SPACE_LIST_RESULT = 'GET_ALL_SPACE_LIST_RESULT';

export const GET_PET_PENDING_LIST = 'GET_PET_PENDING_LIST';
export const GET_PET_PENDING_LIST_RESULT = 'GET_PET_PENDING_LIST_RESULT';

export const UPDATE_VENUE_LIST_ADMIN = 'UPDATE_VENUE_LIST_ADMIN';
export const UPDATE_VENUE_LIST_ADMIN_RESULT = 'UPDATE_VENUE_LIST_ADMIN_RESULT';

//* ** SERVICE SCREEN DETAILS */
export const GET_ALL_SERVICE_LIST = 'GET_ALL_SERVICE_LIST';
export const GET_ALL_SERVICE_LIST_RESULT = 'GET_ALL_SERVICE_LIST_RESULT';

export const GET_PET_SERVICE_PENDING_LIST = 'GET_PET_SERVICE_PENDING_LIST';
export const GET_PET_SERVICE_PENDING_LIST_RESULT = 'GET_PET_SERVICE_PENDING_LIST_RESULT';

export const UPDATE_SERVICE_LIST_ADMIN = 'UPDATE_SERVICE_LIST_ADMIN';
export const UPDATE_SERVICE_LIST_ADMIN_RESULT = 'UPDATE_SERVICE_LIST_ADMIN_RESULT';

/// ** BOOKINGS  */

export const GET_SERVICES_BOOKING = 'GET_SERVICES_BOOKING';
export const GET_SERVICES_BOOKING_RESULT = 'GET_SERVICES_BOOKING_RESULT';

export const GET_VENUE_BOOKING = 'GET_VENUE_BOOKING';
export const GET_VENUE_BOOKING_RESULT = 'GET_VENUE_BOOKING_RESULT';

/// *** DASHBOARD *////
export const GET_TOTAL_SERVICE_BOOKING = 'GET_TOTAL_SERVICE_BOOKING';
export const GET_TOTAL_SERVICE_BOOKING_RESULT = 'GET_TOTAL_SERVICE_BOOKING_RESULT';

export const GET_TOTAL_VENUE_BOOKING = 'GET_TOTAL_VENUE_BOOKING';
export const GET_TOTAL_VENUE_BOOKING_RESULT = 'GET_TOTAL_VENUE_BOOKING_RESULT';

export const GET_TOTAL_BOOKINGS = 'GET_TOTAL_BOOKINGS';
export const GET_TOTAL_BOOKINGS_RESULT = 'GET_TOTAL_BOOKINGS_RESULT';

/** TERMS AND CONDITON */
export const GET_TERMS_AND_CONDITION = 'GET_TERMS_AND_CONDITION';
export const GET_TERMS_AND_CONDITION_RESULT = 'GET_TERMS_AND_CONDITION_RESULT';

export const CREATE_TERMS_AND_CONDITIION = 'CREATE_TERMS_AND_CONDITIION';
export const CREATE_TERMS_AND_CONDITIION_RESULT = 'CREATE_TERMS_AND_CONDITIION_RESULT';

export const UPDATE_TERMS_AND_CONDITION = 'UPDATE_TERMS_AND_CONDITION';
export const UPDATE_TERMS_AND_CONDITION_RESULT = 'UPDATE_TERMS_AND_CONDITION_RESULT';

/** * LOGIN  */
export const CREATE_ADMIN_LOGIN = 'CREATE_ADMIN_LOGIN';
export const CREATE_ADMIN_LOGIN_RESULT = 'CREATE_ADMIN_LOGIN_RESULT';
export const LOGIN_STATUS = 'LOGIN_STATUS';

/** ABOUT US */
export const GET_ABOUT_DETAILS = 'GET_ABOUT_DETAILS';
export const GET_ABOUT_DETAILS_RESULT = 'GET_ABOUT_DETAILS_RESULT';

export const CREATE_ABOUT_DETAILS = 'CREATE_ABOUT_DETAILS';
export const CREATE_ABOUT_DETAILS_RESULT = 'CREATE_ABOUT_DETAILS_RESULT';

export const UPDATED_ABOUT = 'UPDATED_ABOUT';
export const UPDATED_ABOUT_REUSLT = 'UPDATED_ABOUT_REUSLT';

/** PRIVACY POLICY */

export const GET_PRIVACY_POLICY = 'GET_PRIVACY_POLICY';
export const GET_PRIVACY_POLICY_RESULT = 'GET_PRIVACY_POLICY_RESULT';

export const CREATE_PRIVACY_POLICY = 'CREATE_PRIVACY_POLICY';
export const CREATE_PRIVACY_POLICY_RESULT = 'CREATE_PRIVACY_POLICY_RESULT';

export const UPDATE_PRIVCACY_POLICY = 'UPDATE_PRIVCACY_POLICY';
export const UPDATE_PRIVCACY_POLICY_RESULT = 'UPDATE_PRIVCACY_POLICY_RESULT';
